version: "3.5"

services:
  flsp-app:
    image: flsp-app:latest
    build: ./flsp-app
    env_file:
      - config.env
    labels:
      # tells traefik to route traffic with Host flsp.davgra.com to flsp-app
      - "traefik.http.routers.flsp-app.rule=Host(`flsp.davgra.com`)"
      # enable automatic certificate generation
      - "traefik.http.routers.flsp-app.tls.certresolver=le"
      - "traefik.http.routers.flsp-app.entrypoints=websecure"
      # tell traefik to use different port
      - "traefik.http.services.flsp-app.loadbalancer.server.port=3000"
      # use dgserv3
      - "traefik.docker.network=dgserv3"
    ports:
      - 3000:3000
    networks:
      - dgserv3
      - flsp_network

  flsp-core:
    image: flsp-core:latest
    build: ./flsp-core
    env_file:
      - config.env
    networks:
      - flsp_network

  flsp-db:
    image: flsp-db:latest
    build: ./flsp-db
    env_file:
      - config.env
    ports:
      - 5432:5432
    networks:
      - flsp_network

networks:
  dgserv3:
    name: dgserv3
    external: true
  flsp_network:
    name: flsp_network
